language: "english" # avoid using abbreviations as they might confuse gigaChat
model: "GigaChat-2" # using GigaChat Lite — model that is suitable for solving simpler tasks that require maximum speed
scope: "GIGACHAT_API_PERS" # current version of API 
token_endpoint: "https://ngw.devices.sberbank.ru:9443/api/v2/oauth" # endpoint currently used to request OAuth2 access tokens
chat_endpoint: "https://gigachat.devices.sberbank.ru/api/v1/chat/completions" # endpoint currently used to send request to gigaChat
auth_key: "insert_your_authorization_key_here" #  get your key from your personal account at developers.sber.ru
